// travels-react/src/components/topbar.tsx
import Image from "next/image";
import Link from "next/link";

export default function Topbar() {
  return (
    <>
      <main className="topbar">
      <Image
                src="/Pulpi-React.png"
                alt="Logo de React encima del pulpo de la pulpoConf"
                width="50"
                height="70"
              />

        <h1>Mi app de viajes</h1>

        <div className="topbar__menu">
        <Link href="/" className="topbar__menuOption">Home</Link>
        <Link href="/travels" className="topbar__menuOption">Travels List</Link>
        {/* <Link
            href={{
              pathname: '/travel-edit/[slug]',
              query: { slug: 0 },
            }}
          >
            Travel edit
          </Link> */}
        </div>
        
      </main>
    </>
  );
}

// travels-angular/src/app/components/top-bar/top-bar.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-top-bar',
  standalone: true,
  imports: [RouterOutlet, RouterLink, RouterLinkActive],
  templateUrl: './top-bar.component.html',
  styleUrl: './top-bar.component.scss'
})
export class TopBarComponent {

}

<div class="top-bar">
  <img
    src="images/Pulpi-Angular.png"
    alt="logo de angular encima del pulpo de la pulpoConf"
    class="top-bar__logo"
  />

  <h1>Mi app de viajes</h1>

  <div class="top-bar__menu">
    <a
      routerLink=""
      routerLinkActive="active"
      ariaCurrentWhenActive="page"
      class="top-bar__menu-option"
      >Home</a
    >
    <a
      routerLink="travels"
      routerLinkActive="active"
      ariaCurrentWhenActive="page"
      class="top-bar__menu-option"
      >Travels List</a
    >
  </div>
</div>
